on:
  push:
    branches:
      - "master"
      - "!dev/**"
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
