on:
  push:
    branches:
      - "main"
      - "!dev/**"
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # build against antecedant mods PR
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@2042
