on:
  push:
    branches:
      - "main"
      - "!dev/**"
    paths:
      - "!**.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
